### ISSUE TITLE
Provide linter for pre-commit and pull request

### ISSUE THREAD

**Issue by EricBeach** [GoogleCloudPlatform/pontem#15]
Use google-java-format tool to perform both pre-commit linting as well as pull request linting. The later would be accomplished via Travis.

**Comment by mirons-google** [comment]
This can be done with `checkstyle` and the accompanying Google Style.

**Comment by EricBeach** [comment]
Since our pom.xml now depends upon https://github.com/apache/beam/blob/master/pom.xml#L1540 we get style checking every build.

**Comment by mirons-google** [comment]
Great is this in Google style and is it checked as part of the Travis UNIT_TESTS or E2E_TESTS (newly instituted in this [PR](https://github.com/GoogleCloudPlatform/pontem/pull/49))

**Comment by EricBeach** [comment]
It is slightly different than the Google style. It will run as part of Travis.
