### ISSUE TITLE
Can't interleaved children of single root table restore in parallel

### ISSUE THREAD

**Issue by katsew** [GoogleCloudPlatform/pontem#64]
I've tried to restore some interleaved tables, but it's too slow to finish,
since they execute in series after restored the parent table. :(

Here's how Dataflow job created.  
Parent -> Child01 -> Child02 -> Child03...ChildN

I think restore of children could be parallel.
Please improve it, thanks.

**Comment by EricBeach** [comment]
The children cannot be restored in parallel to their parents because writing a child cell requires the parent cell to be present.

**Comment by EricBeach** [comment]
If it is too slow, you need to increase Dataflow workers and Cloud Spanner nodes.
