### ISSUE TITLE
Do not clobber existing backup data files

### ISSUE THREAD

**Issue by nielm** [GoogleCloudPlatform/pontem#69]
When backing up, pontem should check if the destination directory is empty (or non-existent), and fail if not.

This is to prevent a backup in progress overwriting a backup that already exists. There are 2 reasons for this: 
1) if the new backup process fails, the existing backup is corrupted.
2) if the existing backup has more rows in a table than the new one, it may have more data files, which are not then overwritten by the new backup. Should this backup be restored, data from the older backup will also be restored.

If the user _wants_ to store the backup in a constant directory name, this can be achieved by backing up to an empty temp directory, then renaming it once the backup is successful.

**Comment by EricBeach** [comment]
Fixed
